# Local/On-premise Cluster Config.
#
# Created by the system administrator to launch Ray cluster over on-premise machines.
# The system administrator must have `sudo` access to the local nodes.
# Requirements:
#   1) Python (> 3.6) on all nodes   
#   2) Ray CLI (= 1.10.0) on all nodes
#
# Example usage:
#   >> sky admin deploy cluster-config.yaml

cluster:
  ips: [3.142.141.133, 3.144.206.91]
  name: dev-production 

# Authentication into Local cluster nodes
auth:
  ssh_user: ubuntu
  ssh_private_key: ~/.ssh/ubuntu.pem
