name: Release Build

on:
  push:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version from branch name
        id: determine_version
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/heads\/releases\//}"

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ steps.determine_version.outputs.VERSION }}
        run: |
          docker build -t skypilot:${{ env.VERSION }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push skypilot:${{ env.VERSION }}
